cloudflare:
  email: "brett@easyml.app"
  api_token: 2xN4rKvqoIl57SsqOEfcqJYyrhIRL1nGoTlWTbi2
  account_id: b1daa612e4da6b19c66166224635e713
  deploy_env: production
  r2_endpoint: https://b1daa612e4da6b19c66166224635e713.r2.cloudflarestorage.com
  r2_bucket: deploys
  r2_region: auto
  r2_access_key_id: b407c638840af1c4b9ebe25e23a3d2cb
  r2_secret_access_key: 944106cb0a45a5b1c6a75e7a8abf0ba4bf56070b8e1c7dec91634e99c3c29b23
  analytics_endpoint: https://api.cloudflare.com/client/v4/graphql
  blocked_domains_list_id: 090cda6998554527bf656fac18efebda
