default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DB_HOST"] %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: nichefinder_development

test:
  <<: *default
  database: nichefinder_test

staging:
  <<: *default
  database: nichefinder_staging
  username: jumpstart
  password: <%= ENV["POSTGRES_PASSWORD"] %>

production:
  <<: *default
  database: nichefinder_production
  username: nichefinder
  password: <%= ENV["POSTGRES_PASSWORD"] %>
