launch:
  steps:
    brainstorm:
      order: 1
    website:
      order: 2
    ad_campaign:
      order: 3
      substeps:
        - content
        - highlights
        - keywords
        - settings
        - launch
    launch:
      order: 4
      substeps:
        - settings
        - review
        - deployment
