/** @type {import('@remix-run/dev').AppConfig} */
export default {
  ignoredRouteFiles: ["**/.*"],
  serverModuleFormat: "esm",
  serverMinify: false,
  serverDependenciesToBundle: [
    /@langchain\/.*/,
    "langchain",
    "langsmith",
    "ai",
    "@ai-sdk/.*",
    "zod",
    "drizzle-.*",
    "pg",
    "ioredis",
    "jose",
    "fast-json-stable-stringify",
    "date-fns",
    "diff",
    "lodash",
    "random-words",
    "sax",
    "shiki",
    "unist-util-visit",
    "yargs",
  ],
  watchPaths: ["./app/lib/.server/**/*"],
  serverBuildPath: "build/index.js",
  assetsBuildDirectory: "build/client",
  publicPath: "/build/",
  future: {
    v3_fetcherPersist: true,
    v3_relativeSplatPath: true,
    v3_throwAbortReason: true,
  }
};
