import { test, expect, loginUser } from "./fixtures/auth";
import { DatabaseSnapshotter } from "./fixtures/database";
import { DashboardPage } from "./pages/dashboard.page";

/**
 * Dashboard E2E Tests
 *
 * Tests the analytics dashboard including:
 * - Performance charts (leads, CPL, CTR, page views)
 * - AI-generated insights (via Langgraph)
 * - Project cards and filtering
 * - Date range switching
 *
 * Uses analytics snapshots to set up different data scenarios.
 * Insights are generated by Langgraph when the dashboard loads.
 */
test.describe("Dashboard", () => {
  let dashboardPage: DashboardPage;

  test.describe("With Healthy Account (analytics/healthy_account)", () => {
    test.beforeEach(async ({ page }) => {
      await DatabaseSnapshotter.restoreSnapshot("analytics/healthy_account");
      await loginUser(page);
      dashboardPage = new DashboardPage(page);
    });

    test("displays dashboard structure correctly", async ({ page }) => {
      await dashboardPage.goto();

      // Check main sections are visible
      await expect(page.locator("h1")).toContainText("Welcome Back");
      await expect(page.getByText("Key Insights")).toBeVisible();
      await expect(page.getByText("Performance Overview")).toBeVisible();
      await expect(page.getByText("Projects").first()).toBeVisible();
    });

    test("displays performance charts with data", async ({ page }) => {
      await dashboardPage.goto();

      // Check all 4 metric charts are visible
      await expect(page.getByText("Total Leads")).toBeVisible();
      await expect(page.getByText("Cost-per-Lead")).toBeVisible();
      await expect(page.getByText("Click-Through Rate")).toBeVisible();
      await expect(page.getByText("Page Views")).toBeVisible();

      // Charts should have SVG elements (Recharts renders SVGs)
      const charts = page.locator(".recharts-surface");
      await expect(charts.first()).toBeVisible({ timeout: 10000 });
    });

    test("displays project cards", async ({ page }) => {
      await dashboardPage.goto();

      // Should have 3 projects from healthy_account snapshot
      const projectCards = page.locator('a[href*="/projects/"][href*="/website"]');
      await expect(projectCards).toHaveCount(3);

      // Check project names from the snapshot
      await expect(page.getByText("Premium Pet Portraits")).toBeVisible();
      await expect(page.getByText("Budget Travel Guides")).toBeVisible();
      await expect(page.getByText("Fitness Coaching")).toBeVisible();
    });

    test("displays project metrics on cards", async ({ page }) => {
      await dashboardPage.goto();

      // Each project card should show metrics
      const firstProject = page.locator('a[href*="/projects/"]').first();
      await expect(firstProject.getByText("Leads")).toBeVisible();
      await expect(firstProject.getByText("Page Views")).toBeVisible();
      await expect(firstProject.getByText("CTR")).toBeVisible();
      await expect(firstProject.getByText("Cost-per-Lead")).toBeVisible();
    });

    test("allows filtering projects by status", async ({ page }) => {
      await dashboardPage.goto();

      // Filter tabs should be visible
      await expect(page.getByRole("button", { name: /All/i })).toBeVisible();
      await expect(page.getByRole("button", { name: /Live/i })).toBeVisible();
      await expect(page.getByRole("button", { name: /Paused/i })).toBeVisible();
      await expect(page.getByRole("button", { name: /Draft/i })).toBeVisible();

      // Click Live filter
      await page.getByRole("button", { name: /Live/i }).click();

      // Should still see projects (all are live in healthy_account)
      const projectCards = page.locator('a[href*="/projects/"][href*="/website"]');
      const count = await projectCards.count();
      expect(count).toBeGreaterThan(0);
    });

    test("allows changing date range", async ({ page }) => {
      await dashboardPage.goto();

      // Find the date range dropdown
      const dateFilter = page.locator("select").first();
      await expect(dateFilter).toBeVisible();

      // Should default to 30 days
      await expect(dateFilter).toHaveValue("30");

      // Change to 7 days
      await dateFilter.selectOption("7");
      await expect(dateFilter).toHaveValue("7");

      // Change to 90 days
      await dateFilter.selectOption("90");
      await expect(dateFilter).toHaveValue("90");

      // Charts should still be visible (instant client-side switching)
      await expect(page.getByText("Total Leads")).toBeVisible();
    });

    test("generates and displays insights from Langgraph", async ({ page }) => {
      await dashboardPage.goto();

      // Wait for insights to load (Langgraph will generate them)
      // Insights section should show either:
      // 1. Generated insight cards (3 of them)
      // 2. Empty state if generation is still pending
      const insightsSection = page.locator("section").filter({ hasText: "Key Insights" });
      await expect(insightsSection).toBeVisible();

      // Wait for insight cards to appear (Langgraph generates 3)
      const insightCards = insightsSection.locator('[class*="rounded-lg border p-4"]');
      await expect(insightCards.first()).toBeVisible({ timeout: 30000 });

      // Should have exactly 3 insights
      await expect(insightCards).toHaveCount(3);
    });

    test("insight cards have correct structure", async ({ page }) => {
      await dashboardPage.goto();

      // Wait for insights to load
      const insightsSection = page.locator("section").filter({ hasText: "Key Insights" });
      const insightCards = insightsSection.locator('[class*="rounded-lg border p-4"]');
      await expect(insightCards.first()).toBeVisible({ timeout: 30000 });

      // Each insight should have title, description, and action link
      const firstInsight = insightCards.first();
      await expect(firstInsight.locator("h3")).toBeVisible();
      await expect(firstInsight.locator("p")).toBeVisible();
      await expect(firstInsight.locator("a")).toBeVisible();
    });

    test("insight action links navigate to project pages", async ({ page }) => {
      await dashboardPage.goto();

      // Wait for insights to load
      const insightsSection = page.locator("section").filter({ hasText: "Key Insights" });
      const insightCards = insightsSection.locator('[class*="rounded-lg border p-4"]');
      await expect(insightCards.first()).toBeVisible({ timeout: 30000 });

      // Get the action link from the first insight
      const firstInsight = insightCards.first();
      const actionLink = firstInsight.locator("a");
      const href = await actionLink.getAttribute("href");

      // Should link to a project page
      expect(href).toMatch(/^\/projects\//);

      // Click the link and verify navigation
      await actionLink.click();
      await page.waitForURL(/\/projects\//);
    });

    test("project cards navigate to website page", async ({ page }) => {
      await dashboardPage.goto();

      // Click on first project
      const projectCard = page.locator('a[href*="/projects/"][href*="/website"]').first();
      await projectCard.click();

      // Should navigate to website page
      await page.waitForURL(/\/projects\/[\w-]+\/website/);
    });
  });

  test.describe("With Stalled Project (analytics/stalled_project)", () => {
    test.beforeEach(async ({ page }) => {
      await DatabaseSnapshotter.restoreSnapshot("analytics/stalled_project");
      await loginUser(page);
      dashboardPage = new DashboardPage(page);
    });

    test("displays dashboard with stalled project data", async ({ page }) => {
      await dashboardPage.goto();

      // Should show all 3 projects
      const projectCards = page.locator('a[href*="/projects/"][href*="/website"]');
      await expect(projectCards).toHaveCount(3);

      // Budget Travel Guides is the stalled project
      await expect(page.getByText("Budget Travel Guides")).toBeVisible();
    });

    test("generates insights that flag stalled project", async ({ page }) => {
      await dashboardPage.goto();

      // Wait for insights to load
      const insightsSection = page.locator("section").filter({ hasText: "Key Insights" });
      const insightCards = insightsSection.locator('[class*="rounded-lg border p-4"]');
      await expect(insightCards.first()).toBeVisible({ timeout: 30000 });

      // Should have 3 insights
      await expect(insightCards).toHaveCount(3);

      // At least one insight should mention the stalled project or stalling
      const allText = await insightsSection.textContent();
      const mentionsStall =
        allText?.toLowerCase().includes("stall") ||
        allText?.toLowerCase().includes("budget travel") ||
        allText?.toLowerCase().includes("no lead") ||
        allText?.toLowerCase().includes("days");

      // The LLM should detect and flag the stalled project
      expect(mentionsStall).toBe(true);
    });
  });

  test.describe("With Struggling Account (analytics/struggling_account)", () => {
    test.beforeEach(async ({ page }) => {
      await DatabaseSnapshotter.restoreSnapshot("analytics/struggling_account");
      await loginUser(page);
      dashboardPage = new DashboardPage(page);
    });

    test("displays dashboard with struggling metrics", async ({ page }) => {
      await dashboardPage.goto();

      // Should show the single project
      const projectCards = page.locator('a[href*="/projects/"][href*="/website"]');
      await expect(projectCards).toHaveCount(1);

      await expect(page.getByText("My First Startup")).toBeVisible();
    });

    test("generates insights for struggling account", async ({ page }) => {
      await dashboardPage.goto();

      // Wait for insights to load
      const insightsSection = page.locator("section").filter({ hasText: "Key Insights" });
      const insightCards = insightsSection.locator('[class*="rounded-lg border p-4"]');
      await expect(insightCards.first()).toBeVisible({ timeout: 30000 });

      // Should have 3 insights even with bad data
      await expect(insightCards).toHaveCount(3);
    });
  });

  test.describe("With New Account (analytics/new_account)", () => {
    test.beforeEach(async ({ page }) => {
      await DatabaseSnapshotter.restoreSnapshot("analytics/new_account");
      await loginUser(page);
      dashboardPage = new DashboardPage(page);
    });

    test("displays dashboard for new account with minimal data", async ({ page }) => {
      await dashboardPage.goto();

      // Should show the single new project
      const projectCards = page.locator('a[href*="/projects/"][href*="/website"]');
      await expect(projectCards).toHaveCount(1);

      await expect(page.getByText("My New Business")).toBeVisible();
    });

    test("generates encouraging insights for new account", async ({ page }) => {
      await dashboardPage.goto();

      // Wait for insights to load
      const insightsSection = page.locator("section").filter({ hasText: "Key Insights" });
      const insightCards = insightsSection.locator('[class*="rounded-lg border p-4"]');
      await expect(insightCards.first()).toBeVisible({ timeout: 30000 });

      // Should have 3 insights
      await expect(insightCards).toHaveCount(3);

      // New accounts should get positive/encouraging insights
      const hasPositiveCard = await insightsSection.locator('[class*="bg-green-50"]').count();
      expect(hasPositiveCard).toBeGreaterThanOrEqual(1);
    });
  });

  test.describe("With Basic Account (no analytics data)", () => {
    test.beforeEach(async ({ page }) => {
      await DatabaseSnapshotter.restoreSnapshot("website_deployed");
      await loginUser(page);
      dashboardPage = new DashboardPage(page);
    });

    test("displays dashboard with empty/minimal state", async ({ page }) => {
      await dashboardPage.goto();

      // Dashboard structure should still be visible
      await expect(page.locator("h1")).toContainText("Welcome Back");
      await expect(page.getByText("Key Insights")).toBeVisible();
      await expect(page.getByText("Performance Overview")).toBeVisible();
    });

    test("shows project card even without analytics data", async ({ page }) => {
      await dashboardPage.goto();

      // Should have at least one project from website_deployed snapshot
      const projectCards = page.locator('a[href*="/projects/"][href*="/website"]');
      const count = await projectCards.count();
      expect(count).toBeGreaterThanOrEqual(1);
    });

    test("charts show empty state or minimal data", async ({ page }) => {
      await dashboardPage.goto();

      // Charts section should be visible
      await expect(page.getByText("Total Leads")).toBeVisible();

      // May show "No data available yet" for some charts
      // Or show charts with minimal/zero data
      const performanceSection = page
        .locator("section")
        .filter({ hasText: "Performance Overview" });
      await expect(performanceSection).toBeVisible();
    });
  });
});
