import { Website, type ThemeType, type ThemeVariantType } from "@types";
import { renderPrompt, toXML } from '@prompts';

export const websiteThemePrompt = async({theme}: {theme: ThemeType }): Promise<string> => {
    return renderPrompt(toXML({ 
      values: theme, 
      tag: "theme" 
    }))
}

const cleanupClassName = (className: string) => className.replace(/^\-/g, "");

// was themeContextPrompt
export const componentThemePrompt = async ({ themeVariant }: { themeVariant: ThemeVariantType }): Promise<string> => {
    const bgClass = cleanupClassName(themeVariant.backgroundClass);
    const fgClass = cleanupClassName(themeVariant.foregroundClass);
    const fgMutedClass = cleanupClassName(themeVariant.mutedClass);
    const fgPrimaryClass = cleanupClassName(themeVariant.primaryClass);
    const fgSecondaryClass = cleanupClassName(themeVariant.secondaryClass);
    const fgAccentClass = cleanupClassName(themeVariant.accentClass);

    return renderPrompt(`
      <theme>
          You are generating React/ShadCN/Tailwind UI components styled using a predefined 
          set of CSS variables generated by a ColorThemeService. This service ensures
          high accessibility standards are built into the theme.

          <core-principle>
            Core Principle: The Contrast-Guaranteed Pairing System. These classes 
            have been generated for you. You just need to use the right semantic 
            classes based on the context.
          </core-principle>

          <structure>
            --[variable] (e.g., --primary, --card --background): The background 
            color for that element.
            --[variable]-foreground (e.g., --primary-foreground, --card-foreground 
            --background-foreground): The primary foreground color FOR THAT COLOR 
            BACKGROUND. This offers the highest visual emphasis and robust contrast.
            --[variable]-foreground-muted (e.g., --primary-foreground-muted, 
            --card-foreground-muted --background-foreground-muted): The secondary/muted 
            foreground color FOR THAT COLOR BACKGROUND. This offers lower visual emphasis 
            (useful for helper text, captions, etc.) while still ensuring readability.
          </structure>
            
          <contrast-guarantee>
            The service guarantees that both --[variable]-foreground AND 
            --[variable]-foreground-muted meet at least WCAG AA contrast 
            (4.5:1) when used directly on their corresponding --[variable] 
            background.
          </contrast-guarantee>
            
          <special-case>
            Special Case (--muted background):
              --muted paired with --muted-foreground meets 4.5:1.
              --muted paired with --muted-foreground-muted meets 4.5:1.
              Additionally, both --muted-foreground and --muted-foreground-muted 
              are checked to ensure at least 3.0:1 contrast against --background 
              AND --card (prioritizing the 4.5:1 against --muted).
              Mandatory Usage: You MUST use one of the designated foreground variants 
              (-foreground or -foreground-muted) for the color of any text or meaningful 
              icon placed directly on top of its corresponding background variable 
              (--[variable]).
          </special-case>

          <important>
            IMPORTANT: --muted-foreground is ONLY guaranteed to be visible 
            against --muted background. DO NOT USE --muted-foreground against 
            ANY OTHER background color. Use their own --muted definition (e.g. 
            --card-foreground-muted, --primary-foreground-muted)
          </important>

          <trust-system>
            Trust the System: Assume the contrast for both foreground variants 
            against their direct background is sufficient (4.5:1). Your task is 
            to apply the correct variant(s) based on semantic meaning and desired 
            emphasis.
          </trust-system>

          <variables>
            Provided variables (FOR YOUR SECTION, in order to ensure visual appeal and high contrast across sections, you have been assigned to use ONLY the follow variables, if at all possible):
            The background class you should use for this section is: ${bgClass}
            The plain text color class you should use for this section is: ${fgClass}
            The muted text color class you should use for this section is: ${fgMutedClass}
            The primary text color class (for very high visual/brand emphasis) you should use for this section is: ${fgPrimaryClass}
            The secondary text color class (for less important text) you should use for this section is: ${fgSecondaryClass}
            The accent text color class (for brand-specific text) you should use for this section is: ${fgAccentClass}
          </variables>
      </theme>
    `);
}