source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby file: ".ruby-version"

gem "rails", "~> 8.0.0"
gem "propshaft", "~> 1.0"
gem "pg"
gem "puma", "~> 6.0"
gem "importmap-rails"
gem "turbo-rails", "~> 2.0.3"
gem "stimulus-rails", "~> 1.0", ">= 1.0.2"
gem "jbuilder", github: "excid3/jbuilder", branch: "fix-caching-with-api-controllers" # "~> 2.12"
gem "redis"
gem "tzinfo-data", platforms: %i[windows jruby]
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"
gem "bootsnap", ">= 1.4.2", require: false
gem "kamal", ">= 2.0.0.rc2", require: false
gem "thruster", require: false
gem "image_processing", "~> 1.12"
gem "sidekiq-unique-jobs", "~> 8.0"
gem "historiographer"
gem "neighbor"
gem "flipper"
gem "dotenv"
gem "devise-jwt"
gem "activerecord-import"

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "annotate"
  gem "pry"
end

group :development do
  gem "web-console", ">= 4.1.0"
end

group :test do
  gem "capybara", ">= 3.39"
  gem "selenium-webdriver", ">= 4.20.1"
end

# Jumpstart Pro dependencies
require_relative "lib/jumpstart/lib/jumpstart/configuration"
eval_gemfile "Gemfile.jumpstart"

gem "strong_migrations"
gem "inertia_rails", "~> 3.8"
gem "vite_rails", "~> 3.0"
