source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby file: ".ruby-version"

gem "rails", "~> 8.0.0"
gem "carrierwave"
gem "carrierwave-aws"
gem "propshaft", "~> 1.0"
gem "pg"
gem "puma", "~> 6.0"
gem "importmap-rails"
gem "turbo-rails", "~> 2.0.3"
gem "stimulus-rails", "~> 1.0", ">= 1.0.2"
gem "jbuilder", github: "excid3/jbuilder", branch: "fix-caching-with-api-controllers" # "~> 2.12"
gem "redis"
gem "tzinfo-data", platforms: %i[windows jruby]
gem "solid_cache"
gem "solid_queue"

# AWS SDK for R2/S3 uploads
gem "aws-sdk-s3", "~> 1.0"
gem "solid_cable"
gem "bootsnap", ">= 1.4.2", require: false
gem "kamal", ">= 2.0.0.rc2", require: false
gem "thruster", require: false
gem "image_processing", "~> 1.12"
gem "sidekiq-unique-jobs", "~> 8.0"
gem "historiographer", "~> 4.4.4"
gem "neighbor"
gem "flipper"
gem "dotenv"
gem "devise-jwt"
gem "activerecord-import"
gem "typhoeus"
gem "rollbar"
gem "zhong"
gem "sinatra", require: false # Required for Zhong web
gem "rswag"
gem "uuid7"

group :development, :test do
  gem "annotaterb"
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "pry"
  gem "rspec", "~> 3.13"
  gem "rspec-rails", "~> 8.0"
  gem "guard"
  gem "guard-rails", require: false
  gem "guard-rspec", require: false
  gem "factory_bot_rails"
end

group :development do
  gem "web-console", ">= 4.1.0"
end

group :test do
  gem "capybara", ">= 3.39"
  gem "selenium-webdriver", ">= 4.20.1"
  gem "faker"
  gem "timecop"
  gem "shoulda-matchers", "~> 6.0"
  gem "database_cleaner-active_record"
end

# Jumpstart Pro dependencies
require_relative "lib/jumpstart/lib/jumpstart/configuration"
eval_gemfile "Gemfile.jumpstart"

gem "strong_migrations"
gem "inertia_rails", "~> 3.8"
gem "vite_rails", "~> 3.0"
