volumes:
  langgraph_data:
    driver: local
services:
  langgraph-redis:
    image: redis:6
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 1s
      retries: 5
  langgraph-api:
    image: nichefinder
    ports:
      - '2024:8000'
    depends_on:
      langgraph-redis:
        condition: service_healthy
    build:
      context: ../.. # mono repo root
    env_file:
      - .env.docker
    environment:
      REDIS_URI: redis://langgraph-redis:6379
      POSTGRES_URI: postgres://postgres:postgres@host.docker.internal:5432/bolt_development?sslmode=disable
      DATABASE_URI: postgres://postgres:postgres@host.docker.internal:5432/bolt_development?sslmode=disable
