import { type Page, type Locator, expect } from "@playwright/test";

/**
 * Page Object Model for the Dashboard page.
 * Encapsulates interactions with the analytics dashboard.
 */
export class DashboardPage {
  readonly page: Page;

  // Sections
  readonly insightsSection: Locator;
  readonly performanceSection: Locator;
  readonly projectsSection: Locator;

  // Controls
  readonly dateRangeFilter: Locator;
  readonly statusFilterTabs: Locator;

  constructor(page: Page) {
    this.page = page;

    // Main sections
    this.insightsSection = page.locator("section").filter({ hasText: "Key Insights" });
    this.performanceSection = page.locator("section").filter({ hasText: "Performance Overview" });
    this.projectsSection = page.locator("section").filter({ hasText: /^Projects$/ });

    // Controls
    this.dateRangeFilter = page.locator("select").first();
    this.statusFilterTabs = page.locator('[class*="flex items-center gap-2 mb-4"]');
  }

  /**
   * Navigate to the dashboard
   */
  async goto(): Promise<void> {
    await this.page.goto("/dashboard");
    // Wait for the welcome heading to be visible
    await this.page.locator("h1").waitFor({ state: "visible", timeout: 15000 });
  }

  /**
   * Wait for insights to load (generated by Langgraph)
   */
  async waitForInsights(timeout: number = 30000): Promise<void> {
    const insightCards = this.insightsSection.locator('[class*="rounded-lg border p-4"]');
    await insightCards.first().waitFor({ state: "visible", timeout });
  }

  /**
   * Get insight cards
   */
  getInsightCards(): Locator {
    return this.insightsSection.locator('[class*="rounded-lg border p-4"]');
  }

  /**
   * Get project cards
   */
  getProjectCards(): Locator {
    return this.page.locator('a[href*="/projects/"][href*="/website"]');
  }

  /**
   * Change date range filter
   */
  async selectDateRange(days: 7 | 30 | 90): Promise<void> {
    await this.dateRangeFilter.selectOption(String(days));
  }

  /**
   * Filter projects by status
   */
  async filterByStatus(status: "All" | "Live" | "Paused" | "Draft"): Promise<void> {
    await this.page.getByRole("button", { name: new RegExp(status, "i") }).click();
  }
}
