import { z } from "zod";
import { Runnable } from "@langchain/core/runnables";
import type { LangGraphRunnableConfig } from "@langchain/langgraph";
import { v4 as uuidv4 } from "uuid";
import { type CodeTask, CodeTaskType, CodeTaskAction } from "@shared/models/codeTask";
import { type CachePolicy } from "@langgraph/ext/redisCache";
import { withCaching } from "@nodes/core/templates/base/caching";

export enum AdsTaskType {
    CREATE_CAMPAIGN = "CREATE_CAMPAIGN",
    CREATE_AD_GROUP = "CREATE_AD_GROUP",
    CREATE_AD = "CREATE_AD",
}

export enum LLMTaskType {
    ...CodeTaskType,
    ...AdsTaskType,
}
export enum ActionType {
    CREATE = "CREATE",
    UPDATE = "UPDATE",
    DELETE = "DELETE",
}

export enum TaskStatus {
    PENDING = "PENDING",
    IN_PROGRESS = "IN_PROGRESS",
    SUCCESS = "SUCCESS",
    FAILED = "FAILED"
}

export type CodeAsset = {
    type: "CODE_ASSET",
    filePath: string,
    fileSpec: string,
    content: string,
}

export type CampaignAsset = {
    type: "CAMPAIGN_ASSET",
    name: string,
    id: string,
    status: string,
    budget: string,
}

export type AdAsset = {
    type: "AD_ASSET",
    name: string,
    id: string,
    creative: string;
}

export type AdsAsset = CampaignAsset | AdAsset
export type Asset = CodeAsset | AdsAsset;

const assetSchema = z.discriminatedUnion("type", [
  z.object({
    type: z.literal("CODE_ASSET"),
    filePath: z.string(),
    fileSpec: z.string(),
    content: z.string(),
  }),
  z.object({
    type: z.literal("CAMPAIGN_ASSET"),
    name: z.string(),
    id: z.string(),
    status: z.string(),
    budget: z.string(),
  }),
  z.object({
    type: z.literal("AD_ASSET"),
    name: z.string(),
    id: z.string(),
    creative: z.string(),
  }),
]);

const llmTaskSchema = z.object({
  id: z.string().describe("Unique identifier for this action."),
  title: z.string().describe("The title of this action."),
  action: z.nativeEnum(ActionType).describe("The type of action to perform."),
  taskType: z.nativeEnum(LLMTaskType).optional().describe("The action to perform."),
  status: z.nativeEnum(TaskStatus).describe("The status of this action."),
  assets: z.array(assetSchema).optional().describe("The assets generated by this action."),
});

export type LLMTask = z.infer<typeof llmTaskSchema>;

type TitleRecord = { title: string };
type BuildTaskTitleFn<GraphState> = (input: GraphState) => TitleRecord;

const buildFullTask = <GraphState>(
    input: GraphState, 
    buildTaskTitleFn: BuildTaskTitleFn<GraphState>,
    action: ActionType,
    taskType: LLMTaskType,
    status: TaskStatus,
): LLMTask => {
    const task: TitleRecord = buildTaskTitleFn(input);

    return {
        ...task,
        id: uuidv4(),
        action,
        status,
        taskType,
    }
}

function notifyFn(eventName: string, config?: LangGraphRunnableConfig, task?: LLMTask) {
    if (!task) {
        return;
    }

    const writer = config?.writer;
    if (!writer) {
        return;
    }

    writer({
        id: task?.id,
        event: eventName,
        task: task
    })
}

export function notifyStart(config?: LangGraphRunnableConfig, task?: LLMTask) {
    notifyFn("NOTIFY_TASK_START", config, task);
}

export function notifyComplete(config?: LangGraphRunnableConfig, task?: LLMTask) {
    notifyFn("NOTIFY_TASK_COMPLETE", config, task);
}

export function notifyError(config?: LangGraphRunnableConfig, task?: LLMTask) {
    notifyFn("NOTIFY_TASK_ERROR", config, task);
}

export async function withInfrastructure<GraphState extends Record<string, any>>(
    name: string,
    fn: (input: GraphState, config?: LangGraphRunnableConfig) => Promise<Partial<GraphState>>,
    input: GraphState,
    config?: LangGraphRunnableConfig,
    action: ActionType,
    taskType: LLMTaskType,
    status: TaskStatus,
    options?: {
        buildTaskTitle?: BuildTaskTitleFn<GraphState>;
        cachePolicy?: CachePolicy;
    }
): Promise<Partial<GraphState>> {
    console.log(`--- Running ${name} ---`);
    
    const cachedFn = options?.cachePolicy 
        ? withCaching<GraphState>(name, fn, options.cachePolicy)
        : fn;
    
    let task: LLMTask | undefined;
    if (options?.buildTaskTitle) {
        task = buildFullTask(input, options.buildTaskTitle, action, taskType, status);
    }

    try {
        notifyStart(config, task);
        const result = await cachedFn(input, config);
        notifyComplete(config, task);
        return result;
    } catch (error) {
        console.error(`${name} failed:`, error);
        notifyError(config, task);
        throw new Error(`${name} Error: ${String(error)}`);
    }
}