# Admin/Internal API worker configuration
name = "landing-page-server-admin"
main = "src/index-admin.tsx"
compatibility_date = "2024-09-23"
account_id = "e18bb4a0cdad8679a28c8bdfcfed3741"
compatibility_flags = ["nodejs_compat"]
observability = { enabled = true }

routes = [
  { pattern = "atlas-admin.launch10.com/*", zone_name = "launch10.com" }
]

[[kv_namespaces]]
binding = "DEPLOYS_KV"
id = "bc5f59801b704f668f3acee75915fddb"

[[r2_buckets]]
binding = "DEPLOYS_R2"
bucket_name = "deploys"