# Public-facing worker configuration
name = "landing-page-server"
main = "src/index-public.tsx"
account_id = "e18bb4a0cdad8679a28c8bdfcfed3741"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
observability = { enabled = true }

routes = [
  { pattern = "*.launch10.site/*", zone_name = "launch10.site" }
]

# R2 Buckets for different environments
[[r2_buckets]]
binding = "DEPLOYS_R2"
bucket_name = "deploys"

[[kv_namespaces]]
binding = "DEPLOYS_KV"
id = "bc5f59801b704f668f3acee75915fddb"

[durable_objects]
bindings = []

[[durable_objects.migrations]]
tag = "v1"
deleted_classes = ["FirewallDO"]
