import { type GraphState } from "@shared/state/graph";
import { PromptTemplate } from "@langchain/core/prompts";
import { type SectionTheme } from "@models/section";

// Maybe use during update?
const generalOverview = `
    You are generating React/ShadCN/Tailwind UI components styled using a predefined set of CSS variables generated by a ColorThemeService. This service ensures high accessibility standards are built into the theme.

    Core Principle: The Contrast-Guaranteed Pairing System (Background/Foreground/Foreground Muted system)

    1. The ColorThemeService generates CSS variables in specific, contrast-guaranteed sets. 
    2. For variables intended as backgrounds, there are two foreground options provided (foreground and foreground-muted)

    Structure:
    --[variable] (e.g., --primary, --card): The background color.
    --[variable]-foreground (e.g., --primary-foreground, --card-foreground): The primary foreground color. This offers the highest visual emphasis and robust contrast.
    --[variable]-foreground-muted (e.g., --primary-foreground-muted, --card-foreground-muted): The secondary/muted foreground color. This offers lower visual emphasis (useful for helper text, captions, etc.) while still ensuring readability.

    Contrast Guarantee: The service guarantees that both --[variable]-foreground AND --[variable]-foreground-muted meet at least WCAG AA contrast (4.5:1) when used directly on their corresponding --[variable] background.

    Special Case (--muted background):
    --muted paired with --muted-foreground meets 4.5:1.
    --muted paired with --muted-foreground-muted meets 4.5:1.
    Additionally, both --muted-foreground and --muted-foreground-muted are checked to ensure at least 3.0:1 contrast against --background AND --card (prioritizing the 4.5:1 against --muted).
    Mandatory Usage: You MUST use one of the designated foreground variants (-foreground or -foreground-muted) for the color of any text or meaningful icon placed directly on top of its corresponding background variable (--[variable]).

    3. General Rules for Component Generation
    Rule 1: Use Semantic Variables: Always use the provided CSS variables (e.g., var(--primary)) instead of hardcoding hex values.
    Rule 2: Adhere to Pairings: For text/icons on var(--some-variable), use either var(--some-variable-foreground) or var(--some-variable-foreground-muted) for the color. Choose based on desired emphasis.
    Use -foreground for standard/primary text.
    Use -foreground-muted for secondary/less important text on the same background.
    Rule 3: Default Text: For standard text on the main page background, use the background color assigned to you (--background, --primary, --secondary, etc.), and the foreground color assigned to you (--foreground, --primary-foreground, --secondary-foreground, etc.).
    Rule 4: For high-contrast headers (e.g. h1, h2, h3, etc.) IF you are assigned the standard --background, use --primary or --secondary for text emphasis.
    Rule 5: Container Text: For text inside elements using var(--card) or var(--popover), use var(--card-foreground) or var(--popover-foreground) for primary text, and var(--card-foreground-muted) or var(--popover-foreground-muted) for secondary text.
    Rule 6: Avoid Mixing Pairs: Do NOT use a foreground variable with the wrong background variable (e.g., var(--primary-foreground) on var(--secondary)). Contrast is not guaranteed.
    Rule 7: Trust the System: Assume the contrast for both foreground variants against their direct background is sufficient (4.5:1). Your task is to apply the correct variant(s) based on semantic meaning and desired emphasis.

    4. Provided variables (ENSURE SEMANTIC CORRECTNESS — USE THE CORRECT FOREGROUND VARIANT BASED ON SEMANTIC MEANING)
    The background class you should use for this section is: bg{bgClass}
    The plain text color class you should use for this section is: text{fgClass}
    The muted text color class you should use for this section is: text{fgMutedClass}
    The primary text color class (for very high visual/brand emphasis) you should use for this section is: text{fgPrimaryClass}
    The secondary text color class (for less important text) you should use for this section is: text{fgSecondaryClass}
    The accent text color class (for brand-specific text) you should use for this section is: text{fgAccentClass}

    The application has a color theme defined by the following variables:
    {theme}
`
const baseTemplate = PromptTemplate.fromTemplate(`
    You are generating React/ShadCN/Tailwind UI components styled using a predefined set of CSS variables generated by a ColorThemeService. This service ensures high accessibility standards are built into the theme.

    Core Principle: The Contrast-Guaranteed Pairing System. These classes have been generated for you. You just need to use the right semantic classes based on the context.

    Structure:
    --[variable] (e.g., --primary, --card --background): The background color for that element.
    --[variable]-foreground (e.g., --primary-foreground, --card-foreground --background-foreground): The primary foreground color FOR THAT COLOR BACKGROUND. This offers the highest visual emphasis and robust contrast.
    --[variable]-foreground-muted (e.g., --primary-foreground-muted, --card-foreground-muted --background-foreground-muted): The secondary/muted foreground color FOR THAT COLOR BACKGROUND. This offers lower visual emphasis (useful for helper text, captions, etc.) while still ensuring readability.

    Contrast Guarantee: The service guarantees that both --[variable]-foreground AND --[variable]-foreground-muted meet at least WCAG AA contrast (4.5:1) when used directly on their corresponding --[variable] background.

    Special Case (--muted background):
    --muted paired with --muted-foreground meets 4.5:1.
    --muted paired with --muted-foreground-muted meets 4.5:1.
    Additionally, both --muted-foreground and --muted-foreground-muted are checked to ensure at least 3.0:1 contrast against --background AND --card (prioritizing the 4.5:1 against --muted).
    Mandatory Usage: You MUST use one of the designated foreground variants (-foreground or -foreground-muted) for the color of any text or meaningful icon placed directly on top of its corresponding background variable (--[variable]).

    IMPORTANT: --muted-foreground is ONLY guaranteed to be visible against --muted background. DO NOT USE --muted-foreground against ANY OTHER background color. Use their own --muted definition (e.g. --card-foreground-muted, --primary-foreground-muted)

    Trust the System: Assume the contrast for both foreground variants against their direct background is sufficient (4.5:1). Your task is to apply the correct variant(s) based on semantic meaning and desired emphasis.

    Provided variables (FOR YOUR SECTION, in order to ensure visual appeal and high contrast across sections, you have been assigned to use ONLY the follow variables, if at all possible):
    The background class you should use for this section is: bg{bgClass}
    The plain text color class you should use for this section is: text{fgClass}
    The muted text color class you should use for this section is: text{fgMutedClass}
    The primary text color class (for very high visual/brand emphasis) you should use for this section is: text{fgPrimaryClass}
    The secondary text color class (for less important text) you should use for this section is: text{fgSecondaryClass}
    The accent text color class (for brand-specific text) you should use for this section is: text{fgAccentClass}
`);

const cleanupClassName = (className: string) => className.replace(/^\-/g, "");

export const themeContext = async (themeMap: SectionTheme): Promise<string> => {
    const sectionTheme = themeMap;
    const bgClass = cleanupClassName(sectionTheme.backgroundClass);
    const fgClass = cleanupClassName(sectionTheme.foregroundClass);
    const fgMutedClass = cleanupClassName(sectionTheme.mutedClass);
    const fgPrimaryClass = cleanupClassName(sectionTheme.primaryClass);
    const fgSecondaryClass = cleanupClassName(sectionTheme.secondaryClass);
    const fgAccentClass = cleanupClassName(sectionTheme.accentClass);

    const themeString = await baseTemplate.format({ 
        bgClass,
        fgClass,
        fgMutedClass,
        fgPrimaryClass,
        fgSecondaryClass,
        fgAccentClass
    });
    return themeString;
};